### ISSUE TITLE
minor value errors

### ISSUE THREAD

**Issue by NoHalfBits** [ruuvi/ruuvi-sensor-protocols#19]
_Data Format 3 Protocol Specification -> Data field descriptions -> Atmospheric Pressure_:
'65536' and '115536' (2x) should be '65535' and '115535' 

_Data Format 3 Protocol Specification -> Data field descriptions -> Battery voltage_:
again '65536' is out of uint16 range, should be '65535'

_Data Format 5 Protocol Specification -> Data field descriptions -> Humidity_:
Example value '10010' when multiplied by 0.0025 results in '25.025', not '25.050'
(found by my spec-based unit tests failing ;))

_Data Format 5 Protocol Specification -> Data field descriptions -> Atmospheric Pressure_:
'Values supported (...) 115536' should be '115535'

**Comment by ojousima** [comment]
I've forgotten to reply to this issue, sorry about that. It has been fixed earlier on, thanks for noting it.
