### ISSUE TITLE
Issue in parsing Ruuvi tag data

### ISSUE THREAD

**Issue by TaherianuBeac** [ruuvi/ruuvi-sensor-protocols#20]
Hi, 
This is the data that I've got from my ruuvi tag. I am trying to parse this data. Could you please help me to know how I can parse this data because it seems is different from the types that you introduced in your documents.
0201060303AAFE1716AAFE10F9037275752E76692F2342434158414D4F3039
Thank you

**Comment by ojousima** [comment]
It looks like your RuuviTag is in URL mode where the tag sends data encoded inside Eddystone URL. Please press button "B" on RuuviTag and verify that the red led is blinking, you should then get the raw binary data.

**Comment by ojousima** [comment]
Closing as stale
