### ISSUE TITLE
Secure format 08: Measurement sequence is 16 bits Should be larger

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi-sensor-protocols#25]
As per prior discussions a 16 bit Measurement sequence number rolls over too soon. 
It should be 24 bits

**Comment by ojousima** [comment]
We'll leave this open for a while, if there is no other required use for the reserved bytes the sequence can be expanded.

**Comment by johanneshauer** [comment]
I'd like the movement detection counter to be (much) bigger then 8bit/254 values. I'm living in the 5th floor and would like to track traffic and weather.

**Comment by ojousima** [comment]
Movement counter is already 16 bits in this format. The measurement sequence counter is big enough to avoid duplicate data, and rollover isn't a problem in most applications. It would be possible to add a GATT connection command to read sensor uptime.  Closing this for now

**Comment by DG12** [comment]
Quoting from my own forum posting:
"C) Measurement sequence number of 2 bytes at a transmission period as used by RawV2_slow of 6.240 seconds causes this to wrap after only 4.7 days"

After working with the ruuvis for over 3 years and gaining a better understanding to the values,  I have not found a reason to expand the measurement Sequence number.

@Gr4v1t0 I believe you are referring to MovementCounter which is not this issue.
I think there is another reference to increasing the size of MovementCounter  but I cannot locate it at this time.
