### ISSUE TITLE
Secure format 08 needs accelerometer values

### ISSUE THREAD

**Issue by DG12** [ruuvi/ruuvi-sensor-protocols#28]
X/Y/Z accelerometer values need to be added.

See also forum discussion regarding moving battery and TX to alternate packet.

**Comment by ojousima** [comment]
There's 3 bytes free, maybe those could be dedicated to accelerometer? 
It would prevent adding a third or fourth byte to sequence counter as suggested in #25 though

**Comment by DG12** [comment]
My recent revelation with regard to the accelerometer, i.e. it's reporting of the orientation of the tag, makes me think of a few possible uses right away (See garage door monitor in forums and I'll post a water level monitor soon) using only the Z orientation.  I am having a little trouble imagining how to use the X & Y values in addition. 

Added 2021-10-23 : seer gaining a better understanding of accelerometer I now understand that at least one additional value is necessary to determine orientation since Z is the same if orientation is \ and /.


Since it wasn't until recently I that I understood the the Z axis maybe if someone could give me an example of a use for all 3 orientations 

Please see my recent discussion on the [forum](https://f.ruuvi.com/t/proposal-for-secure-data-format/3756)

**Comment by ojousima** [comment]
We'll leave the extra bytes as "reserved" for now. I'm sure that they can find good use as a status/counter bits for things like HALL sensors etc, but it's easier to consider the use cases once the format is implemented.
