### ISSUE TITLE
Are these documents up to date? Duplicated info with docs.ruuvi.com

### ISSUE THREAD

**Issue by laurijamsa** [ruuvi/ruuvi-sensor-protocols#31]
Maybe this repo should be removed?

**Comment by DG12** [comment]
I updated this repo yesterday. (just added pull request now)

[docs.ruuvi.com](http://docs.ruuvi.com) that I can see is woefully incomplete

Neither I nor another "contributor" can update docs.ruuvi.com :-(

**Comment by ojousima** [comment]
I will archive this repository. Docs can be edited through pull requests at https://github.com/ruuvi/docs
